# Site information
base_url = "https://makenorth.ca"
title = "MakeNorth"
description = "MakeNorth is TKTK"
default_language = "en"

# Build options
compile_sass = false
build_search_index = false
minify_html = false

# Generate RSS and Atom feeds; we set the global generate_feeds to 'false' and
# then set it to true in the blog section, so that we're not publishing new
# feeds every time we update the home or about pages.
generate_feeds = false
feed_filenames = [
  "atom.xml", # must be first, so it's the default
  "rss.xml",  # also supported
]

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

theme = "serene"

# TODO: when the following issue is fixed, use this:
# https://github.com/getzola/zola/issues/2677
ignored_static = [
  #"*/typst-auto-render.js",
  #"*/c2bda2230c7262de9e2a.wasm",
]

[markdown]
# Code highlighting
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]

# Don't use fancy smart punctuation; e.g. copy-pasting to a terminal annoying.
smart_punctuation = false

# Controls how external links are rendered
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"


# ================================================================================


[extra]
name = "MakeNorth"
id = "makenorth"
bio = "MakeNorth is TKTK"
avatar = "about:blank"

#avatar = "TODO"

links = [
  { name = "GitHub", icon = "github", url = "https://github.com/MakeNorth" },
  #{ name = "Email", icon = "email", url = "mailto:andrew@makenorth.ca" },
]

# What kind of layout we want on the homepage
homepage_layout = "about"

# Don't force the theme; it defaults to the user's device preference.
force_theme = false

# Configuration for the "recent" layout
recent_max = 10               # Number of recent posts to show
recent_more = true            # Whether to show the "more" link
recent_more_text = "more »"   # Text of the "more" link

# The sections of the website
sections = [
  { name = "blog", path = "/blog", is_external = false },
  #{ name = "projects", path = "/projects", is_external = false },
  { name = "about", path = "/about", is_external = false },
  # { name = "github", path = "https://github.com/<your-username>", is_exteranl = true },
]

# The path to the blog section; must match the path of the blog section in the
# sections array, above.
blog_section_path = "/blog"

# Configuration for the navigation bar
nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

# Configuration 
display_id = false        # Display "@username" in home page
blog_categorized = false  # Break down blog posts by category
blur_effect = true        # Add background blur
back_to_top = true        # Add a "back to top" button to posts


# Configuration for posts
toc = true                # Show table of contents
copy = true               # Show 'copy' button on code blocks
comment = false           # Show comments
display_tags = true       # Show tags at top of post
truncate_summary = false  # Truncate summary from front of post

# Configuration for displaying an "outdated" warning on posts that are older
# than a certain date. Turned off by default, but can be turned on for specific
# posts.
outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

# Put our copyright in the footer, don't show the theme copyright
footer_copyright = "© 2024 MakeNorth"
footer_credits = false

# The text to display in the 404 page
not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
